[build]
target = "./example/gui/index.html"
dist = "./example/gui/web/"
filehash = false

[serve]
port = 8090

[watch]
watch = ["./example/gui/", "./crates/egui-states/src/client/"]
ignore = ["./example/gui/web/"]
