# Generated by build.rs, do not edit
# ruff: noqa: D101 D107
from collections.abc import Callable
from enum import IntEnum

import numpy as np

import egui_states.structures as s
from egui_states.server import StatesBase, StateServerBase
from egui_states.structures import ISubStates


class TestEnum(IntEnum):
    A = 0
    B = 1
    C = 2


class TestEnum2(IntEnum):
    X = 0
    Y = 1
    Z = 2


class MySubState(ISubStates):
    def __init__(self, parent: str):
        self.stat: s.Static[list[float]] = s.Static[list[float]](4, [0, 0])
        self.enum_atomic: s.Value[TestEnum2] = s.Value[TestEnum2](5, TestEnum2.Y)


class Collections(ISubStates):
    def __init__(self, parent: str):
        self.list: s.ValueVec[int] = s.ValueVec[int](6)
        self.map: s.ValueMap[int, int] = s.ValueMap[int, int](7, 8)


class States(StatesBase):
    @staticmethod
    def _get_obj_types() -> list[s.PyObjectType]:
        return [
            s.f64,
            s.emp,
            s.enu(TestEnum),
            s.vec(s.u32),
            s.li(s.f32, 2),
            s.enu(TestEnum2),
            s.i32,
            s.u16,
            s.u32,
            s.st,
        ]

    def __init__(self, server: StateServerBase):
        super().__init__(server)
        parent = "root"
        self.value: s.Value[float] = s.Value[float](0, 0)
        self.empty_signal: s.SignalEmpty = s.SignalEmpty(True)
        self.image: s.ValueImage = s.ValueImage()
        self.graphs: s.ValueGraphs = s.ValueGraphs(np.float32)
        self.test_enum: s.Value[TestEnum] = s.Value[TestEnum](2, TestEnum.B)
        self.map: s.Value[list[int]] = s.Value[list[int]](3, [78, 78, 78, 78])
        self.my_sub_state: MySubState = MySubState(parent + ".my_sub_state")
        self.collections: Collections = Collections(parent + ".collections")
        self.value_take_1: s.ValueTake[str] = s.ValueTake[str](9)
        self.value_take_2: s.ValueTakeEmpty = s.ValueTakeEmpty()


class StatesServer(StateServerBase):
    """The main class for the SteteServer for UI."""

    states: States

    def __init__(
        self,
        port: int,
        signals_workers: int = 3,
        error_handler: Callable[[Exception], None] | None = None,
        ip_addr: tuple[int, int, int, int] | None = None,
        handshake: list[int] | None = None,
        runner_threads: int = 3,
    ) -> None:
        """Initialize the StateServer.

        Args:
            port (int): The port to listen on.
            signals_workers (int, optional): Number of workers for signal processing. Defaults to 3.
            error_handler (Callable[[Exception], None] | None, optional): Error handler function. Defaults to None.
            ip_addr (tuple[int, int, int, int] | None, optional): IP address to bind to. Defaults to None.
            handshake (list[int] | None, optional): Handshake bytes. Defaults to None.
            runner_threads (int): The number of threads for running the server.
        """
        super().__init__(States, port, signals_workers, error_handler, ip_addr, handshake, runner_threads)
