# Generated by build.rs, do not edit
# ruff: noqa: D101 D107
from collections.abc import Callable
from dataclasses import dataclass
from enum import IntEnum

import numpy as np

import egui_states.structures as s
from egui_states.server import StatesBase, StateServerBase
from egui_states.structures import ISubStates


class TestEnum(IntEnum):
    A = 0
    B = 1
    C = 2


class TestEnum2(IntEnum):
    X = 0
    Y = 1
    Z = 2


@dataclass
class TestStruct2(s.CustomStruct):
    enabled: bool
    level: int
    name: str


@dataclass
class TestStruct(s.CustomStruct):
    x: float
    y: float
    label: str


class NestedValueStates(ISubStates):
    def __init__(self, parent: str):
        self.secondary_choice: s.Value[TestEnum2] = s.Value[TestEnum2](8, TestEnum2.Y)
        self.selected_enum: s.Value[TestEnum | None] = s.Value[TestEnum | None](9, None)


class ValueStates(ISubStates):
    def __init__(self, parent: str):
        self.bool_value: s.Value[bool] = s.Value[bool](0, False)
        self.count: s.Value[int] = s.Value[int](1, 0)
        self.ratio: s.Value[float] = s.Value[float](2, 0)
        self.queued_progress: s.Value[float] = s.Value[float](3, 0, True)
        self.title: s.Value[str] = s.Value[str](4, "")
        self.optional_value: s.Value[int | None] = s.Value[int | None](5, None)
        self.fixed_numbers: s.Value[list[int]] = s.Value[list[int]](6, [0, 0, 0])
        self.test_enum: s.Value[TestEnum] = s.Value[TestEnum](7, TestEnum.A)
        self.nested: NestedValueStates = NestedValueStates(parent + ".nested")


class SignalStates(ISubStates):
    def __init__(self, parent: str):
        self.empty_signal: s.SignalEmpty = s.SignalEmpty(True)
        self.number_signal: s.Signal[float] = s.Signal[float](2)
        self.enum_signal: s.Signal[TestEnum] = s.Signal[TestEnum](7, True)


class NestedStaticStates(ISubStates):
    def __init__(self, parent: str):
        self.label: s.Static[str] = s.Static[str](4, "")
        self.enum_hint: s.Static[TestEnum] = s.Static[TestEnum](7, TestEnum.A)


class StaticStates(ISubStates):
    def __init__(self, parent: str):
        self.status_text: s.Static[str] = s.Static[str](4, "")
        self.summary: s.Static[TestStruct2] = s.Static[TestStruct2](11, TestStruct2(False, 0, ""))
        self.pair: s.Static[list[float]] = s.Static[list[float]](12, [0, 0])
        self.nested: NestedStaticStates = NestedStaticStates(parent + ".nested")


class ValueTakeStates(ISubStates):
    def __init__(self, parent: str):
        self.take_text: s.ValueTake[str] = s.ValueTake[str](4)
        self.take_empty: s.ValueTakeEmpty = s.ValueTakeEmpty()


class CustomValueStates(ISubStates):
    def __init__(self, parent: str):
        self.point: s.Value[TestStruct] = s.Value[TestStruct](13, TestStruct(0, 0, ""))
        self.optional_struct: s.Value[TestStruct2 | None] = s.Value[TestStruct2 | None](14, None)


class ValueVecActionStates(ISubStates):
    def __init__(self, parent: str):
        self.append_item: s.SignalEmpty = s.SignalEmpty()
        self.remove_last: s.SignalEmpty = s.SignalEmpty()
        self.reset_demo: s.SignalEmpty = s.SignalEmpty()


class ValueVecStates(ISubStates):
    def __init__(self, parent: str):
        self.items: s.ValueVec[int] = s.ValueVec[int](1)
        self.actions: ValueVecActionStates = ValueVecActionStates(parent + ".actions")


class ValueMapActionStates(ISubStates):
    def __init__(self, parent: str):
        self.insert_next: s.SignalEmpty = s.SignalEmpty()
        self.remove_lowest: s.SignalEmpty = s.SignalEmpty()
        self.reset_demo: s.SignalEmpty = s.SignalEmpty()


class ValueMapStates(ISubStates):
    def __init__(self, parent: str):
        self.items: s.ValueMap[int, int] = s.ValueMap[int, int](15, 16)
        self.actions: ValueMapActionStates = ValueMapActionStates(parent + ".actions")


class NestedDataStates(ISubStates):
    def __init__(self, parent: str):
        self.buffer: s.Data[np.uint16] = s.Data[np.uint16](1)


class DataStates(ISubStates):
    def __init__(self, parent: str):
        self.bytes: s.Data[np.uint8] = s.Data[np.uint8](0)
        self.samples: s.Data[np.float32] = s.Data[np.float32](8)
        self.nested: NestedDataStates = NestedDataStates(parent + ".nested")


class ImageStates(ISubStates):
    def __init__(self, parent: str):
        self.image: s.ValueImage = s.ValueImage()


class States(StatesBase):
    @staticmethod
    def _get_obj_types() -> list[s.PyObjectType]:
        return [
            s.bo,
            s.i32,
            s.f64,
            s.f32,
            s.st,
            s.opt(s.i32),
            s.li(s.u16, 3),
            s.enu(TestEnum),
            s.enu(TestEnum2),
            s.opt(s.enu(TestEnum)),
            s.emp,
            s.cl([s.bo, s.u16, s.st], TestStruct2),
            s.li(s.f32, 2),
            s.cl([s.f32, s.f32, s.st], TestStruct),
            s.opt(s.cl([s.bo, s.u16, s.st], TestStruct2)),
            s.u16,
            s.u32,
        ]

    def __init__(self, server: StateServerBase):
        super().__init__(server)
        parent = "root"
        self.values: ValueStates = ValueStates(parent + ".values")
        self.signals: SignalStates = SignalStates(parent + ".signals")
        self.statics: StaticStates = StaticStates(parent + ".statics")
        self.value_take: ValueTakeStates = ValueTakeStates(parent + ".value_take")
        self.custom_values: CustomValueStates = CustomValueStates(parent + ".custom_values")
        self.value_vec: ValueVecStates = ValueVecStates(parent + ".value_vec")
        self.value_map: ValueMapStates = ValueMapStates(parent + ".value_map")
        self.data: DataStates = DataStates(parent + ".data")
        self.image: ImageStates = ImageStates(parent + ".image")


class StatesServer(StateServerBase):
    """The main class for the SteteServer for UI."""

    states: States

    def __init__(
        self,
        port: int,
        signals_workers: int = 3,
        error_handler: Callable[[Exception], None] | None = None,
        ip_addr: tuple[int, int, int, int] | None = None,
        handshake: list[int] | None = None,
        runner_threads: int = 3,
    ) -> None:
        """Initialize the StateServer.

        Args:
            port (int): The port to listen on.
            signals_workers (int, optional): Number of workers for signal processing. Defaults to 3.
            error_handler (Callable[[Exception], None] | None, optional): Error handler function. Defaults to None.
            ip_addr (tuple[int, int, int, int] | None, optional): IP address to bind to. Defaults to None.
            handshake (list[int] | None, optional): Handshake bytes. Defaults to None.
            runner_threads (int): The number of threads for running the server.
        """
        super().__init__(States, port, signals_workers, error_handler, ip_addr, handshake, runner_threads)
