class PyObjectType:
    """A class representing a type of object in the state server."""

    @staticmethod
    def u8(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def u16(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def u32(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def u64(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def i8(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def i16(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def i32(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def i64(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def f32(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def f64(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def boolean(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def string(optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def empty() -> PyObjectType: ...
    @staticmethod
    def tuple_(elements: list[PyObjectType], optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def list_(element_type: PyObjectType, size: int, optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def vec(element_type: PyObjectType, optional: bool = False) -> PyObjectType: ...
    @staticmethod
    def map(key_type: PyObjectType, value_type: PyObjectType, optional: bool = False) -> PyObjectType: ...
