from collections.abc import Buffer
from typing import Any

from egui_states.custom_types import CustomStruct, FastEnum

class PyObjectType:
    """A class representing a type of object in the state server."""

u8: PyObjectType
u16: PyObjectType
u32: PyObjectType
u64: PyObjectType
i8: PyObjectType
i16: PyObjectType
i32: PyObjectType
i64: PyObjectType
f32: PyObjectType
f64: PyObjectType
bo: PyObjectType
st: PyObjectType
emp: PyObjectType

def opt(pytype: PyObjectType) -> PyObjectType: ...
def tu(elements: list[PyObjectType]) -> PyObjectType: ...
def cl(elements: list[PyObjectType], class_type: type[CustomStruct]) -> PyObjectType: ...
def li(element_type: PyObjectType, size: int) -> PyObjectType: ...
def vec(element_type: PyObjectType) -> PyObjectType: ...
def map(key_type: PyObjectType, value_type: PyObjectType) -> PyObjectType: ...
def enu(enum_obj: type[FastEnum]) -> PyObjectType: ...

class StateServerCore:
    """A class representing the core functionality of the state server."""

    def __init__(
        self, port: int, ip_addr: tuple[int, int, int, int] | None = None, handshake: list[int] | None = None
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def is_connected(self) -> bool: ...
    def disconnect_client(self) -> None: ...
    def update(self, duration: float | None = None) -> None: ...

    # values ----------------------------------------------------------------------
    def value_set(self, value_id: int, value: object, set_signal: bool, update: bool) -> None: ...
    def value_get(self, value_id: int) -> Any: ...

    # static ----------------------------------------------------------------------
    def static_set(self, value_id: int, value: object, update: bool) -> None: ...
    def static_get(self, value_id: int) -> Any: ...

    # signals ---------------------------------------------------------------------
    def signal_set(self, value_id: int, value: object) -> None: ...
    def signal_set_register(self, value_id: int, register: bool) -> None: ...
    def signal_get(self, last_id: int | None) -> tuple[int, object]: ...
    def signal_set_to_multi(self, value_id: int) -> None: ...
    def signal_set_to_single(self, value_id: int) -> None: ...

    # lists -----------------------------------------------------------------------
    def list_set(self, value_id: int, value: list[object], update: bool) -> None: ...
    def list_get(self, value_id: int) -> list[object]: ...
    def list_set_item(self, value_id: int, idx: int, value: object, update: bool) -> None: ...
    def list_get_item(self, value_id: int, idx: int) -> object: ...
    def list_del_item(self, value_id: int, idx: int, update: bool) -> None: ...
    def list_append_item(self, value_id: int, value: object, update: bool) -> None: ...
    def list_len(self, value_id: int) -> int: ...

    # map ------------------------------------------------------------------------
    def map_set(self, value_id: int, value: dict[Any, Any], update: bool) -> None: ...
    def map_get(self, value_id: int) -> dict[Any, Any]: ...
    def map_set_item(self, value_id: int, key: object, value: object, update: bool) -> None: ...
    def map_get_item(self, value_id: int, key: object) -> object: ...
    def map_del_item(self, value_id: int, key: object, update: bool) -> None: ...
    def map_len(self, value_id: int) -> int: ...

    # image -----------------------------------------------------------------------
    def image_set(
        self,
        value_id: int,
        image: Buffer,
        update: bool,
        origin: list[int] | tuple[int, int] | None = None,
    ) -> None: ...
    def image_get(self, value_id: int) -> tuple[bytearray, tuple[int, int]]: ...
    def image_size(self, value_id: int) -> tuple[int, int]: ...

    # graphs ----------------------------------------------------------------------
    def graph_set(self, value_id: int, idx: int, graph: Buffer, update: bool) -> None: ...
    def graph_add_points(
        self,
        value_id: int,
        idx: int,
        graph: Buffer,
        update: bool,
    ) -> None: ...
    def graph_get(self, value_id: int, idx: int) -> tuple[bytes, int, tuple[int, int]]: ...
    def graph_count(self, value_id: int) -> int: ...
    def graph_remove(self, value_id: int, idx: int, update: bool) -> None: ...
    def graph_reset(self, value_id: int, update: bool) -> None: ...

    # add states ------------------------------------------------------------------
    def add_value(self, name: str, object_type: PyObjectType, initial_value: object) -> None: ...
    def add_static(self, name: str, object_type: PyObjectType, initial_value: object) -> None: ...
    def add_signal(self, name: str, object_type: PyObjectType) -> None: ...
    def add_list(self, name: str, object_type: PyObjectType) -> None: ...
    def add_map(self, name: str, key_type: PyObjectType, value_type: PyObjectType) -> None: ...
    def add_image(self, name: str) -> None: ...
    def add_graphs(self, name: str, is_double: bool) -> None: ...
