//! Typed state synchronization between an [`egui`](https://docs.rs/egui) client
//! and a Rust or Python server.
//!
//! A client describes its state tree with [`State`] implementations (normally
//! generated by the [`State`](derive@State) derive), constructs it with
//! [`ClientBuilder`], and uses the returned handles from the UI. Enable the
//! `server` feature for the native Rust server API, or `build_scripts` to
//! generate a server whose state tree exactly matches the client.

extern crate self as egui_states;

mod collections;
mod data_transport;
mod event;
mod hashing;
mod image_transport;
mod serialization;
mod typed;

#[cfg(feature = "build_scripts")]
/// Build-time generators for typed Rust and Python server bindings.
pub mod build_scripts;
#[cfg(feature = "client")]
mod client;
#[cfg(feature = "python")]
/// Python extension-module support used by the `egui-states` Python package.
pub mod python;
#[cfg(feature = "server")]
/// Native Rust server API.
pub mod server;
#[cfg(any(feature = "server", feature = "python"))]
mod server_core;

#[cfg(feature = "client")]
pub use client::{
    atomics::{Atomic, AtomicLock, AtomicLockStatic, AtomicStatic, FallbackLock, UpdateLock},
    client::ClientBuilder,
    client::{Client, ConnectionState},
    data::{Data, DataMulti},
    data_take::{DataMultiTake, DataTake},
    image::Image,
    initial_value::{InitValue, InitialValue},
    states_creator::StatesCreator,
    value_map::MapState,
    value_vec::VecState,
    values::{
        Diff, DiffAtomic, GetQueueType, NoQueue, Queue, Signal, Static, StaticAtomic, Value,
        ValueAtomic, ValueTake,
    },
};

#[cfg(feature = "client")]
/// A root or nested group of client-side states.
///
/// Prefer deriving this trait with [`State`](derive@State). Field names become
/// segments in the synchronized state path, starting below `root`.
pub trait State {
    /// Stable Rust type name used by server-binding generation.
    const NAME: &'static str;

    /// Constructs the state and registers all of its children with `creator`.
    fn new(c: &mut impl StatesCreator) -> Self;
}

pub use egui_states_macros::typed;
#[cfg(feature = "client")]
pub use egui_states_macros::{Atomic, AtomicStatic, InitialValue, State};
/// Re-export of Serde used by [`typed`] and generated implementations.
pub use serde;
pub use typed::{ObjectType, Typed};

pub(crate) const PROTOCOL_VERSION: u16 = 5;
