[package]
name = "egui_states_macros"
version.workspace = true
edition.workspace = true
resolver = "3"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
