// Generated by build.rs, do not edit
use egui_states::server as s;

#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum TestEnum {
    A = 0,
    B = 1,
    C = 2,
}

unsafe impl egui_states::Transportable for TestEnum {
    fn init_value(&self) -> egui_states::InitValue {
        egui_states::InitValue::Enum(match self {
            Self::A => String::from("A"),
            Self::B => String::from("B"),
            Self::C => String::from("C"),
        })
    }

    fn get_type() -> egui_states::ObjectType {
        egui_states::ObjectType::Enum(
            String::from("TestEnum"),
            vec![
                (String::from("A"), 0),
                (String::from("B"), 1),
                (String::from("C"), 2),
            ],
        )
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum TestEnum2 {
    X = 0,
    Y = 1,
    Z = 2,
}

unsafe impl egui_states::Transportable for TestEnum2 {
    fn init_value(&self) -> egui_states::InitValue {
        egui_states::InitValue::Enum(match self {
            Self::X => String::from("X"),
            Self::Y => String::from("Y"),
            Self::Z => String::from("Z"),
        })
    }

    fn get_type() -> egui_states::ObjectType {
        egui_states::ObjectType::Enum(
            String::from("TestEnum2"),
            vec![
                (String::from("X"), 0),
                (String::from("Y"), 1),
                (String::from("Z"), 2),
            ],
        )
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, egui_states::Transportable)]
pub struct TestStruct2 {
    pub enabled: bool,
    pub level: u16,
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, egui_states::Transportable)]
pub struct TestStruct {
    pub x: f32,
    pub y: f32,
    pub label: String,
}


#[derive(Clone)]
pub struct NestedValueStates {
    pub secondary_choice: s::Value<TestEnum2>,
    pub selected_enum: s::Value<Option<TestEnum>>,
}

impl NestedValueStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            secondary_choice: s::Value::new(server, format!("{parent}.secondary_choice"), TestEnum2::Y, false)?,
            selected_enum: s::Value::new(server, format!("{parent}.selected_enum"), None::<TestEnum>, false)?,
        })
    }
}

#[derive(Clone)]
pub struct ValueStates {
    pub bool_value: s::Value<bool>,
    pub count: s::Value<i32>,
    pub ratio: s::Value<f64>,
    pub queued_progress: s::Value<f32>,
    pub title: s::Value<String>,
    pub optional_value: s::Value<Option<i32>>,
    pub fixed_numbers: s::Value<[u16; 3]>,
    pub test_enum: s::Value<TestEnum>,
    pub nested: NestedValueStates,
}

impl ValueStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            bool_value: s::Value::new(server, format!("{parent}.bool_value"), false, false)?,
            count: s::Value::new(server, format!("{parent}.count"), 0i32, false)?,
            ratio: s::Value::new(server, format!("{parent}.ratio"), 0.0f64, false)?,
            queued_progress: s::Value::new(server, format!("{parent}.queued_progress"), 0.0f32, true)?,
            title: s::Value::new(server, format!("{parent}.title"), String::from(""), false)?,
            optional_value: s::Value::new(server, format!("{parent}.optional_value"), None::<i32>, false)?,
            fixed_numbers: s::Value::new(server, format!("{parent}.fixed_numbers"), [0u16, 0u16, 0u16], false)?,
            test_enum: s::Value::new(server, format!("{parent}.test_enum"), TestEnum::A, false)?,
            nested: NestedValueStates::new(server, &format!("{parent}.nested"))?,
        })
    }
}

#[derive(Clone)]
pub struct SignalStates {
    pub empty_signal: s::Signal<()>,
    pub number_signal: s::Signal<f64>,
    pub enum_signal: s::Signal<TestEnum>,
}

impl SignalStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            empty_signal: s::Signal::<()>::new(server, format!("{parent}.empty_signal"), true)?,
            number_signal: s::Signal::<f64>::new(server, format!("{parent}.number_signal"), false)?,
            enum_signal: s::Signal::<TestEnum>::new(server, format!("{parent}.enum_signal"), true)?,
        })
    }
}

#[derive(Clone)]
pub struct NestedStaticStates {
    pub label: s::Static<String>,
    pub enum_hint: s::Static<TestEnum>,
}

impl NestedStaticStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            label: s::Static::new(server, format!("{parent}.label"), String::from(""))?,
            enum_hint: s::Static::new(server, format!("{parent}.enum_hint"), TestEnum::A)?,
        })
    }
}

#[derive(Clone)]
pub struct StaticStates {
    pub status_text: s::Static<String>,
    pub summary: s::Static<TestStruct2>,
    pub pair: s::Static<[f32; 2]>,
    pub nested: NestedStaticStates,
}

impl StaticStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            status_text: s::Static::new(server, format!("{parent}.status_text"), String::from(""))?,
            summary: s::Static::new(server, format!("{parent}.summary"), TestStruct2 { enabled: false, level: 0u16, name: String::from("") })?,
            pair: s::Static::new(server, format!("{parent}.pair"), [0.0f32, 0.0f32])?,
            nested: NestedStaticStates::new(server, &format!("{parent}.nested"))?,
        })
    }
}

#[derive(Clone)]
pub struct ValueTakeStates {
    pub take_text: s::ValueTake<String>,
    pub take_empty: s::ValueTake<()>,
}

impl ValueTakeStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            take_text: s::ValueTake::<String>::new(server, format!("{parent}.take_text"))?,
            take_empty: s::ValueTake::<()>::new(server, format!("{parent}.take_empty"))?,
        })
    }
}

#[derive(Clone)]
pub struct CustomValueStates {
    pub point: s::Value<TestStruct>,
    pub optional_struct: s::Value<Option<TestStruct2>>,
}

impl CustomValueStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            point: s::Value::new(server, format!("{parent}.point"), TestStruct { x: 0.0f32, y: 0.0f32, label: String::from("") }, false)?,
            optional_struct: s::Value::new(server, format!("{parent}.optional_struct"), None::<TestStruct2>, false)?,
        })
    }
}

#[derive(Clone)]
pub struct ValueVecActionStates {
    pub append_item: s::Signal<()>,
    pub remove_last: s::Signal<()>,
    pub reset_demo: s::Signal<()>,
}

impl ValueVecActionStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            append_item: s::Signal::<()>::new(server, format!("{parent}.append_item"), false)?,
            remove_last: s::Signal::<()>::new(server, format!("{parent}.remove_last"), false)?,
            reset_demo: s::Signal::<()>::new(server, format!("{parent}.reset_demo"), false)?,
        })
    }
}

#[derive(Clone)]
pub struct ValueVecStates {
    pub items: s::VecState<i32>,
    pub actions: ValueVecActionStates,
}

impl ValueVecStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            items: s::VecState::<i32>::new(server, format!("{parent}.items"))?,
            actions: ValueVecActionStates::new(server, &format!("{parent}.actions"))?,
        })
    }
}

#[derive(Clone)]
pub struct ValueMapActionStates {
    pub insert_next: s::Signal<()>,
    pub remove_lowest: s::Signal<()>,
    pub reset_demo: s::Signal<()>,
}

impl ValueMapActionStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            insert_next: s::Signal::<()>::new(server, format!("{parent}.insert_next"), false)?,
            remove_lowest: s::Signal::<()>::new(server, format!("{parent}.remove_lowest"), false)?,
            reset_demo: s::Signal::<()>::new(server, format!("{parent}.reset_demo"), false)?,
        })
    }
}

#[derive(Clone)]
pub struct ValueMapStates {
    pub items: s::MapState<u16, u32>,
    pub actions: ValueMapActionStates,
}

impl ValueMapStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            items: s::MapState::<u16, u32>::new(server, format!("{parent}.items"))?,
            actions: ValueMapActionStates::new(server, &format!("{parent}.actions"))?,
        })
    }
}

#[derive(Clone)]
pub struct NestedDataStates {
    pub buffer: s::Data<u16>,
}

impl NestedDataStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            buffer: s::Data::<u16>::new(server, format!("{parent}.buffer"))?,
        })
    }
}

#[derive(Clone)]
pub struct DataStates {
    pub bytes: s::Data<u8>,
    pub samples: s::Data<f32>,
    pub nested: NestedDataStates,
}

impl DataStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            bytes: s::Data::<u8>::new(server, format!("{parent}.bytes"))?,
            samples: s::Data::<f32>::new(server, format!("{parent}.samples"))?,
            nested: NestedDataStates::new(server, &format!("{parent}.nested"))?,
        })
    }
}

#[derive(Clone)]
pub struct DataTakeStates {
    pub take_buffer: s::DataTake<u8>,
    pub take_samples: s::DataTake<f32>,
}

impl DataTakeStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            take_buffer: s::DataTake::<u8>::new(server, format!("{parent}.take_buffer"))?,
            take_samples: s::DataTake::<f32>::new(server, format!("{parent}.take_samples"))?,
        })
    }
}

#[derive(Clone)]
pub struct NestedMultiDataStates {
    pub buffer: s::DataMulti<u16>,
}

impl NestedMultiDataStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            buffer: s::DataMulti::<u16>::new(server, format!("{parent}.buffer"))?,
        })
    }
}

#[derive(Clone)]
pub struct MultiDataStates {
    pub bytes: s::DataMulti<u8>,
    pub samples: s::DataMulti<f32>,
    pub nested: NestedMultiDataStates,
}

impl MultiDataStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            bytes: s::DataMulti::<u8>::new(server, format!("{parent}.bytes"))?,
            samples: s::DataMulti::<f32>::new(server, format!("{parent}.samples"))?,
            nested: NestedMultiDataStates::new(server, &format!("{parent}.nested"))?,
        })
    }
}

#[derive(Clone)]
pub struct NestedMultiDataTakeStates {
    pub buffer: s::DataMultiTake<u16>,
}

impl NestedMultiDataTakeStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            buffer: s::DataMultiTake::<u16>::new(server, format!("{parent}.buffer"))?,
        })
    }
}

#[derive(Clone)]
pub struct MultiDataTakeStates {
    pub bytes: s::DataMultiTake<u8>,
    pub samples: s::DataMultiTake<f32>,
    pub nested: NestedMultiDataTakeStates,
}

impl MultiDataTakeStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            bytes: s::DataMultiTake::<u8>::new(server, format!("{parent}.bytes"))?,
            samples: s::DataMultiTake::<f32>::new(server, format!("{parent}.samples"))?,
            nested: NestedMultiDataTakeStates::new(server, &format!("{parent}.nested"))?,
        })
    }
}

#[derive(Clone)]
pub struct ImageStates {
    pub image: s::Image,
}

impl ImageStates {
    pub fn new(server: &s::StateServer, parent: &str) -> s::Result<Self> {
        Ok(Self {
            image: s::Image::new(server, format!("{parent}.image"))?,
        })
    }
}

#[derive(Clone)]
pub struct State {
    pub values: ValueStates,
    pub signals: SignalStates,
    pub statics: StaticStates,
    pub value_take: ValueTakeStates,
    pub custom_values: CustomValueStates,
    pub value_vec: ValueVecStates,
    pub value_map: ValueMapStates,
    pub data: DataStates,
    pub data_take: DataTakeStates,
    pub multi_data: MultiDataStates,
    pub data_multi_take: MultiDataTakeStates,
    pub image: ImageStates,
}

impl State {
    pub fn new(server: &s::StateServer) -> s::Result<Self> {
        let parent = "root";
        Ok(Self {
            values: ValueStates::new(server, &format!("{parent}.values"))?,
            signals: SignalStates::new(server, &format!("{parent}.signals"))?,
            statics: StaticStates::new(server, &format!("{parent}.statics"))?,
            value_take: ValueTakeStates::new(server, &format!("{parent}.value_take"))?,
            custom_values: CustomValueStates::new(server, &format!("{parent}.custom_values"))?,
            value_vec: ValueVecStates::new(server, &format!("{parent}.value_vec"))?,
            value_map: ValueMapStates::new(server, &format!("{parent}.value_map"))?,
            data: DataStates::new(server, &format!("{parent}.data"))?,
            data_take: DataTakeStates::new(server, &format!("{parent}.data_take"))?,
            multi_data: MultiDataStates::new(server, &format!("{parent}.multi_data"))?,
            data_multi_take: MultiDataTakeStates::new(server, &format!("{parent}.data_multi_take"))?,
            image: ImageStates::new(server, &format!("{parent}.image"))?,
        })
    }
}

pub struct StatesServer {
    server: s::StateServer,
    pub states: State,
    pub logging: s::LoggingSignal,
}

impl StatesServer {
    pub const VERSION_HASH: u64 = 5850504962483486421;

    pub fn new(port: u16) -> s::Result<Self> {
        Self::with_options(s::ServerOptions::new(port))
    }

    pub fn with_options(options: s::ServerOptions) -> s::Result<Self> {
        let server = s::StateServer::with_options(options)?;
        let states = State::new(&server)?;
        server.finalize()?;
        let logging = s::LoggingSignal::new(&server);
        Ok(Self { server, states, logging })
    }

    pub fn state_server(&self) -> &s::StateServer {
        &self.server
    }

    pub fn start(&self) -> s::Result<()> {
        self.server.start()
    }

    pub fn stop(&self) {
        self.server.stop();
    }

    pub fn update(&self, duration: Option<f32>) -> s::Result<()> {
        self.server.update(duration)
    }

    pub fn disconnect_client(&self) {
        self.server.disconnect_client();
    }

    pub fn is_running(&self) -> bool {
        self.server.is_running()
    }

    pub fn is_connected(&self) -> bool {
        self.server.is_connected()
    }

    pub fn on_connect(&self, callback: impl Fn(String) + Send + Sync + 'static) -> s::CallbackHandle {
        self.server.on_connect(callback)
    }

    pub fn on_disconnect(&self, callback: impl Fn() + Send + Sync + 'static) -> s::CallbackHandle {
        self.server.on_disconnect(callback)
    }

    pub fn on_client_message(&self, callback: impl Fn(String) + Send + Sync + 'static) -> s::CallbackHandle {
        self.server.on_client_message(callback)
    }
}
