[package]
name = "egui_states_pyserver"
version.workspace = true
edition.workspace = true

[dependencies]
pyo3 = ">=0.26"
tungstenite = "0.27"
serde = { workspace = true }

egui_states_core = { workspace = true }
