[build-system]
requires = ["maturin>=1.9"]
build-backend = "maturin"

[project]
name = "states-server"
dynamic = ["version"]
dependencies = ["numpy"]

[tool.maturin]
bindings = "pyo3"
python-packages = ["states_server"]
module-name = "states_server.core"
manifest-path = "Cargo.toml"
