# Generated by build.rs, do not edit
from dataclasses import dataclass
from egui_states.server import StateServerCore
import egui_states.custom_types as cust


class TestEnum(cust.FastEnum):
    A = 0
    B = 1
    C = 2


@dataclass
class TestStruct(cust.CustomStruct):
    x: float
    y: float
    label: str
